<?php

return [
    'currencies' => [
        // Major Global Currencies
        'USD' => ['name' => 'US Dollar', 'symbol' => '$', 'symbol_position' => 'before', 'decimal_places' => 2],
        'EUR' => ['name' => 'Euro', 'symbol' => '€', 'symbol_position' => 'before', 'decimal_places' => 2],
        'GBP' => ['name' => 'British Pound', 'symbol' => '£', 'symbol_position' => 'before', 'decimal_places' => 2],
        'JPY' => ['name' => 'Japanese Yen', 'symbol' => '¥', 'symbol_position' => 'before', 'decimal_places' => 0],
        'CHF' => ['name' => 'Swiss Franc', 'symbol' => 'CHF', 'symbol_position' => 'before', 'decimal_places' => 2],
        'CAD' => ['name' => 'Canadian Dollar', 'symbol' => 'C$', 'symbol_position' => 'before', 'decimal_places' => 2],
        'AUD' => ['name' => 'Australian Dollar', 'symbol' => 'A$', 'symbol_position' => 'before', 'decimal_places' => 2],
        'CNY' => ['name' => 'Chinese Yuan', 'symbol' => '¥', 'symbol_position' => 'before', 'decimal_places' => 2],
        'INR' => ['name' => 'Indian Rupee', 'symbol' => '₹', 'symbol_position' => 'before', 'decimal_places' => 2],
        'BRL' => ['name' => 'Brazilian Real', 'symbol' => 'R$', 'symbol_position' => 'before', 'decimal_places' => 2],
        'RUB' => ['name' => 'Russian Ruble', 'symbol' => '₽', 'symbol_position' => 'after', 'decimal_places' => 2],
        'KRW' => ['name' => 'South Korean Won', 'symbol' => '₩', 'symbol_position' => 'before', 'decimal_places' => 0],
        'SGD' => ['name' => 'Singapore Dollar', 'symbol' => 'S$', 'symbol_position' => 'before', 'decimal_places' => 2],
        'HKD' => ['name' => 'Hong Kong Dollar', 'symbol' => 'HK$', 'symbol_position' => 'before', 'decimal_places' => 2],
        'NZD' => ['name' => 'New Zealand Dollar', 'symbol' => 'NZ$', 'symbol_position' => 'before', 'decimal_places' => 2],
        'MXN' => ['name' => 'Mexican Peso', 'symbol' => '$', 'symbol_position' => 'before', 'decimal_places' => 2],
        'SEK' => ['name' => 'Swedish Krona', 'symbol' => 'kr', 'symbol_position' => 'after', 'decimal_places' => 2],
        'NOK' => ['name' => 'Norwegian Krone', 'symbol' => 'kr', 'symbol_position' => 'after', 'decimal_places' => 2],
        'DKK' => ['name' => 'Danish Krone', 'symbol' => 'kr', 'symbol_position' => 'after', 'decimal_places' => 2],
        'PLN' => ['name' => 'Polish Złoty', 'symbol' => 'zł', 'symbol_position' => 'after', 'decimal_places' => 2],
        'TRY' => ['name' => 'Turkish Lira', 'symbol' => '₺', 'symbol_position' => 'before', 'decimal_places' => 2],
        'ZAR' => ['name' => 'South African Rand', 'symbol' => 'R', 'symbol_position' => 'before', 'decimal_places' => 2],
        'AED' => ['name' => 'UAE Dirham', 'symbol' => 'د.إ', 'symbol_position' => 'after', 'decimal_places' => 2],
        'SAR' => ['name' => 'Saudi Riyal', 'symbol' => '﷼', 'symbol_position' => 'after', 'decimal_places' => 2],
        'ILS' => ['name' => 'Israeli Shekel', 'symbol' => '₪', 'symbol_position' => 'before', 'decimal_places' => 2],
        'THB' => ['name' => 'Thai Baht', 'symbol' => '฿', 'symbol_position' => 'before', 'decimal_places' => 2],
        'MYR' => ['name' => 'Malaysian Ringgit', 'symbol' => 'RM', 'symbol_position' => 'before', 'decimal_places' => 2],
        'IDR' => ['name' => 'Indonesian Rupiah', 'symbol' => 'Rp', 'symbol_position' => 'before', 'decimal_places' => 0],
        'PHP' => ['name' => 'Philippine Peso', 'symbol' => '₱', 'symbol_position' => 'before', 'decimal_places' => 2],
        'VND' => ['name' => 'Vietnamese Dong', 'symbol' => '₫', 'symbol_position' => 'after', 'decimal_places' => 0],
        'EGP' => ['name' => 'Egyptian Pound', 'symbol' => 'E£', 'symbol_position' => 'before', 'decimal_places' => 2],
        'NGN' => ['name' => 'Nigerian Naira', 'symbol' => '₦', 'symbol_position' => 'before', 'decimal_places' => 2],
        'KES' => ['name' => 'Kenyan Shilling', 'symbol' => 'KSh', 'symbol_position' => 'before', 'decimal_places' => 2],
        'UGX' => ['name' => 'Ugandan Shilling', 'symbol' => 'USh', 'symbol_position' => 'after', 'decimal_places' => 0],
        'TZS' => ['name' => 'Tanzanian Shilling', 'symbol' => 'TSh', 'symbol_position' => 'before', 'decimal_places' => 2],
        'RWF' => ['name' => 'Rwandan Franc', 'symbol' => 'FRw', 'symbol_position' => 'after', 'decimal_places' => 0],
        'CDF' => ['name' => 'Congolese Franc', 'symbol' => 'FC', 'symbol_position' => 'after', 'decimal_places' => 2],
        'GHS' => ['name' => 'Ghanaian Cedi', 'symbol' => '₵', 'symbol_position' => 'before', 'decimal_places' => 2],
        'ZMW' => ['name' => 'Zambian Kwacha', 'symbol' => 'ZK', 'symbol_position' => 'before', 'decimal_places' => 2],
        'MAD' => ['name' => 'Moroccan Dirham', 'symbol' => 'د.م.', 'symbol_position' => 'after', 'decimal_places' => 2],
        'DZD' => ['name' => 'Algerian Dinar', 'symbol' => 'د.ج', 'symbol_position' => 'after', 'decimal_places' => 2],
        'TND' => ['name' => 'Tunisian Dinar', 'symbol' => 'د.ت', 'symbol_position' => 'after', 'decimal_places' => 3],
        'LYD' => ['name' => 'Libyan Dinar', 'symbol' => 'ل.د', 'symbol_position' => 'after', 'decimal_places' => 3],
        'SDG' => ['name' => 'Sudanese Pound', 'symbol' => 'ج.س.', 'symbol_position' => 'after', 'decimal_places' => 2],
        'ETB' => ['name' => 'Ethiopian Birr', 'symbol' => 'ብር', 'symbol_position' => 'after', 'decimal_places' => 2],
        'MUR' => ['name' => 'Mauritian Rupee', 'symbol' => '₨', 'symbol_position' => 'before', 'decimal_places' => 2],
        'SCR' => ['name' => 'Seychellois Rupee', 'symbol' => '₨', 'symbol_position' => 'before', 'decimal_places' => 2],
        'BWP' => ['name' => 'Botswana Pula', 'symbol' => 'P', 'symbol_position' => 'before', 'decimal_places' => 2],
        'NAD' => ['name' => 'Namibian Dollar', 'symbol' => '$', 'symbol_position' => 'before', 'decimal_places' => 2],
        'SZL' => ['name' => 'Swazi Lilangeni', 'symbol' => 'E', 'symbol_position' => 'before', 'decimal_places' => 2],
        'LSL' => ['name' => 'Lesotho Loti', 'symbol' => 'L', 'symbol_position' => 'before', 'decimal_places' => 2],
        'MGA' => ['name' => 'Malagasy Ariary', 'symbol' => 'Ar', 'symbol_position' => 'after', 'decimal_places' => 2],
        'MWK' => ['name' => 'Malawian Kwacha', 'symbol' => 'MK', 'symbol_position' => 'before', 'decimal_places' => 2],
        'MZN' => ['name' => 'Mozambican Metical', 'symbol' => 'MT', 'symbol_position' => 'before', 'decimal_places' => 2],
        'BND' => ['name' => 'Brunei Dollar', 'symbol' => 'B$', 'symbol_position' => 'before', 'decimal_places' => 2],
        'MMK' => ['name' => 'Myanmar Kyat', 'symbol' => 'K', 'symbol_position' => 'before', 'decimal_places' => 2],
        'LAK' => ['name' => 'Lao Kip', 'symbol' => '₭', 'symbol_position' => 'after', 'decimal_places' => 0],
        'KHR' => ['name' => 'Cambodian Riel', 'symbol' => '៛', 'symbol_position' => 'after', 'decimal_places' => 2],
        'NPR' => ['name' => 'Nepalese Rupee', 'symbol' => '₨', 'symbol_position' => 'before', 'decimal_places' => 2],
        'BDT' => ['name' => 'Bangladeshi Taka', 'symbol' => '৳', 'symbol_position' => 'before', 'decimal_places' => 2],
        'LKR' => ['name' => 'Sri Lankan Rupee', 'symbol' => '₨', 'symbol_position' => 'before', 'decimal_places' => 2],
        'PKR' => ['name' => 'Pakistani Rupee', 'symbol' => '₨', 'symbol_position' => 'before', 'decimal_places' => 2],
        'AFN' => ['name' => 'Afghan Afghani', 'symbol' => '؋', 'symbol_position' => 'before', 'decimal_places' => 2],
        'IRR' => ['name' => 'Iranian Rial', 'symbol' => '﷼', 'symbol_position' => 'after', 'decimal_places' => 2],
        'IQD' => ['name' => 'Iraqi Dinar', 'symbol' => 'ع.د', 'symbol_position' => 'after', 'decimal_places' => 3],
        'JOD' => ['name' => 'Jordanian Dinar', 'symbol' => 'د.ا', 'symbol_position' => 'after', 'decimal_places' => 3],
        'KWD' => ['name' => 'Kuwaiti Dinar', 'symbol' => 'د.ك', 'symbol_position' => 'after', 'decimal_places' => 3],
        'BHD' => ['name' => 'Bahraini Dinar', 'symbol' => 'ب.د', 'symbol_position' => 'after', 'decimal_places' => 3],
        'OMR' => ['name' => 'Omani Rial', 'symbol' => 'ر.ع.', 'symbol_position' => 'after', 'decimal_places' => 3],
        'QAR' => ['name' => 'Qatari Riyal', 'symbol' => 'ر.ق', 'symbol_position' => 'after', 'decimal_places' => 2],
        'YER' => ['name' => 'Yemeni Rial', 'symbol' => '﷼', 'symbol_position' => 'after', 'decimal_places' => 2],
        'SYP' => ['name' => 'Syrian Pound', 'symbol' => '£S', 'symbol_position' => 'before', 'decimal_places' => 2],
        'LBP' => ['name' => 'Lebanese Pound', 'symbol' => 'ل.ل', 'symbol_position' => 'after', 'decimal_places' => 2],
        'PEN' => ['name' => 'Peruvian Sol', 'symbol' => 'S/', 'symbol_position' => 'before', 'decimal_places' => 2],
        'CLP' => ['name' => 'Chilean Peso', 'symbol' => '$', 'symbol_position' => 'before', 'decimal_places' => 0],
        'COP' => ['name' => 'Colombian Peso', 'symbol' => '$', 'symbol_position' => 'before', 'decimal_places' => 2],
        'ARS' => ['name' => 'Argentine Peso', 'symbol' => '$', 'symbol_position' => 'before', 'decimal_places' => 2],
        'UYU' => ['name' => 'Uruguayan Peso', 'symbol' => '$U', 'symbol_position' => 'before', 'decimal_places' => 2],
        'PYG' => ['name' => 'Paraguayan Guarani', 'symbol' => '₲', 'symbol_position' => 'after', 'decimal_places' => 0],
        'BOB' => ['name' => 'Bolivian Boliviano', 'symbol' => 'Bs.', 'symbol_position' => 'before', 'decimal_places' => 2],
        'VES' => ['name' => 'Venezuelan Bolívar', 'symbol' => 'Bs.S', 'symbol_position' => 'before', 'decimal_places' => 2],
        'CRC' => ['name' => 'Costa Rican Colón', 'symbol' => '₡', 'symbol_position' => 'before', 'decimal_places' => 2],
        'NIO' => ['name' => 'Nicaraguan Córdoba', 'symbol' => 'C$', 'symbol_position' => 'before', 'decimal_places' => 2],
        'HNL' => ['name' => 'Honduran Lempira', 'symbol' => 'L', 'symbol_position' => 'before', 'decimal_places' => 2],
        'GTQ' => ['name' => 'Guatemalan Quetzal', 'symbol' => 'Q', 'symbol_position' => 'before', 'decimal_places' => 2],
        'BZD' => ['name' => 'Belize Dollar', 'symbol' => 'BZ$', 'symbol_position' => 'before', 'decimal_places' => 2],
        'PAB' => ['name' => 'Panamanian Balboa', 'symbol' => 'B/.', 'symbol_position' => 'before', 'decimal_places' => 2],
        'BSD' => ['name' => 'Bahamian Dollar', 'symbol' => '$', 'symbol_position' => 'before', 'decimal_places' => 2],
        'BBD' => ['name' => 'Barbadian Dollar', 'symbol' => '$', 'symbol_position' => 'before', 'decimal_places' => 2],
        'TTD' => ['name' => 'Trinidad and Tobago Dollar', 'symbol' => 'TT$', 'symbol_position' => 'before', 'decimal_places' => 2],
        'JMD' => ['name' => 'Jamaican Dollar', 'symbol' => 'J$', 'symbol_position' => 'before', 'decimal_places' => 2],
        'KYD' => ['name' => 'Cayman Islands Dollar', 'symbol' => 'CI$', 'symbol_position' => 'before', 'decimal_places' => 2],
        'AWG' => ['name' => 'Aruban Florin', 'symbol' => 'ƒ', 'symbol_position' => 'before', 'decimal_places' => 2],
        'ANG' => ['name' => 'Netherlands Antillean Guilder', 'symbol' => 'ƒ', 'symbol_position' => 'before', 'decimal_places' => 2],
        'XCD' => ['name' => 'East Caribbean Dollar', 'symbol' => '$', 'symbol_position' => 'before', 'decimal_places' => 2],
        'XPF' => ['name' => 'CFP Franc', 'symbol' => 'F', 'symbol_position' => 'after', 'decimal_places' => 0],
        'XOF' => ['name' => 'West African CFA Franc', 'symbol' => 'CFA', 'symbol_position' => 'after', 'decimal_places' => 0],
        'XAF' => ['name' => 'Central African CFA Franc', 'symbol' => 'FCFA', 'symbol_position' => 'after', 'decimal_places' => 0],
        'ISK' => ['name' => 'Icelandic Króna', 'symbol' => 'kr', 'symbol_position' => 'after', 'decimal_places' => 0],
        'CZK' => ['name' => 'Czech Koruna', 'symbol' => 'Kč', 'symbol_position' => 'after', 'decimal_places' => 2],
        'HUF' => ['name' => 'Hungarian Forint', 'symbol' => 'Ft', 'symbol_position' => 'after', 'decimal_places' => 2],
        'RON' => ['name' => 'Romanian Leu', 'symbol' => 'lei', 'symbol_position' => 'after', 'decimal_places' => 2],
        'BGN' => ['name' => 'Bulgarian Lev', 'symbol' => 'лв', 'symbol_position' => 'after', 'decimal_places' => 2],
        'HRK' => ['name' => 'Croatian Kuna', 'symbol' => 'kn', 'symbol_position' => 'after', 'decimal_places' => 2],
        'RSD' => ['name' => 'Serbian Dinar', 'symbol' => 'дин.', 'symbol_position' => 'after', 'decimal_places' => 2],
        'MKD' => ['name' => 'Macedonian Denar', 'symbol' => 'ден', 'symbol_position' => 'after', 'decimal_places' => 2],
        'ALL' => ['name' => 'Albanian Lek', 'symbol' => 'Lek', 'symbol_position' => 'after', 'decimal_places' => 2],
        'GEL' => ['name' => 'Georgian Lari', 'symbol' => '₾', 'symbol_position' => 'after', 'decimal_places' => 2],
        'AMD' => ['name' => 'Armenian Dram', 'symbol' => '֏', 'symbol_position' => 'after', 'decimal_places' => 2],
        'AZN' => ['name' => 'Azerbaijani Manat', 'symbol' => '₼', 'symbol_position' => 'after', 'decimal_places' => 2],
        'BYN' => ['name' => 'Belarusian Ruble', 'symbol' => 'Br', 'symbol_position' => 'after', 'decimal_places' => 2],
        'UAH' => ['name' => 'Ukrainian Hryvnia', 'symbol' => '₴', 'symbol_position' => 'after', 'decimal_places' => 2],
        'MDL' => ['name' => 'Moldovan Leu', 'symbol' => 'L', 'symbol_position' => 'before', 'decimal_places' => 2],
        'KZT' => ['name' => 'Kazakhstani Tenge', 'symbol' => '₸', 'symbol_position' => 'after', 'decimal_places' => 2],
        'UZS' => ['name' => 'Uzbekistani Som', 'symbol' => 'сўм', 'symbol_position' => 'after', 'decimal_places' => 2],
        'TJS' => ['name' => 'Tajikistani Somoni', 'symbol' => 'ЅМ', 'symbol_position' => 'after', 'decimal_places' => 2],
        'KGS' => ['name' => 'Kyrgyzstani Som', 'symbol' => 'с', 'symbol_position' => 'after', 'decimal_places' => 2],
        'MNT' => ['name' => 'Mongolian Tögrög', 'symbol' => '₮', 'symbol_position' => 'after', 'decimal_places' => 2],
    ]
];